import Head from 'next/head';
import Header from '@/layout/Header';
import Main from '@/layout/Main';
import { useEffect } from 'react';
import globalStyles from '@/utils/globalCSS';

export default function Home() {
  globalStyles();

  useEffect(() => {
    function toggleScroll() {
      if(window.matchMedia("(max-height:570px)").matches) {
        document.querySelector('body')?.classList.add('scrolled')
      } else {
        window.scrollTo(0, 0)
        document.querySelector('body')?.classList.remove('scrolled')
      }
    }

    if(window.matchMedia("(max-height:570px)").matches) {
      document.querySelector('body')?.classList.add('scrolled')
    }

    window.addEventListener('resize', toggleScroll);

    return () => window.removeEventListener('resize', toggleScroll)
    
  }, [])
  
  return (
    <>
      <Head>
        <title>Lucas Salvador - Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
    </>
  )
}
