import Head from 'next/head'
import { globalCss } from '@stitches/react'
import Header from '@/layout/Header'
import Main from '@/layout/Main'
import { useEffect, useState } from 'react'
import Modal from '@/components/Modal'
import Gallery from '@/components/Gallery'
import ModalInfo from '@/components/ModalInfo'

const globalStyles = globalCss({
  '*': {
    margin: 0,
    padding: 0,
    boxSizing: 'border-box',
    fontFamily: 'Montserrat, sans-serif',
    fontSize: '$sizes$1',
    '&:focus-visible': {
      outline: '2px solid',
      outlineColor: 'rgba(52, 146, 235, 0.5)',
      outlineOffset: '5px'
    },
    '::-webkit-scrollbar': {
      width: '5px',
      height: '5px',
    },
    '::-webkit-scrollbar-track': {
      background: 'rgba(0,0,0,0.1)',
    },
    '::-webkit-scrollbar-thumb': {
      background: 'rgba(0,0,0,0.2)',
    },

  },
  'body': {
    overflowY: 'hidden',
    '&.scrolled': {
      overflowY: 'scroll'
    }
  }
})

export default function Home() {
  globalStyles();
  const [isOpen, setIsOpen] = useState(false)

  useEffect(() => {
    function toggleScroll() {
      if(window.matchMedia("(max-height:570px)").matches) {
        document.querySelector('body')?.classList.add('scrolled')
      } else {
        window.scrollTo(0, 0)
        document.querySelector('body')?.classList.remove('scrolled')
      }
    }

    if(window.matchMedia("(max-height:570px)").matches) {
      document.querySelector('body')?.classList.add('scrolled')
    }

    window.addEventListener('resize', toggleScroll);

    return () => window.removeEventListener('resize', toggleScroll)
    
  }, [])
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => setIsOpen(true)}>Abrir modal</button>
      <Header />
      <Modal isOpen={isOpen} onClose={() => setIsOpen(false)} closeOnOverlayClick >
        <Gallery />
        <ModalInfo />
      </Modal>
      <Main />
    </>
  )
}
