import Head from 'next/head'
import { globalCss } from '@stitches/react'
import Header from '@/layout/Header'
import Main from '@/layout/Main'

const globalStyles = globalCss({
  '*': {
    margin: 0,
    padding: 0,
    boxSizing: 'border-box',
    fontFamily: 'Montserrat, sans-serif',
    fontSize: '$sizes$1',
    '&:focus-visible': {
      outline: '2px solid',
      outlineColor: 'rgba(52, 146, 235, 0.5)',
      outlineOffset: '5px'
    },
    '::-webkit-scrollbar': {
      width: '5px',
      height: '5px'
    },
    '::-webkit-scrollbar-track': {
      background: 'transparent'
    },
    '::-webkit-scrollbar-thumb': {
      background: 'rgba(0,0,0,0.2)',
    },

  },
  'body': {
    overflowY: 'hidden'
  }
})

export default function Home() {
  globalStyles();
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
    </>
  )
}
